/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EligibilityOracleInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "GOVERNANCE_ROLE" | "KEEPER_ROLE" | "blacklistUser" | "getRoleAdmin" | "getSubsidyPercentage" | "grantRole" | "hasRole" | "isEligibleForSubsidy" | "minTradeSize" | "renounceRole" | "revokeRole" | "setMinTradeSize" | "setVolumeThreshold" | "supportsInterface" | "updateStakingTier" | "updateUserVolume" | "users" | "volumeThreshold" | "whitelistUser"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EligibilityUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "UserBlacklisted" | "UserWhitelisted"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GOVERNANCE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'KEEPER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'blacklistUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSubsidyPercentage', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isEligibleForSubsidy', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'minTradeSize', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMinTradeSize', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setVolumeThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateStakingTier', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateUserVolume', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'users', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'volumeThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'whitelistUser', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GOVERNANCE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'KEEPER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blacklistUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSubsidyPercentage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEligibleForSubsidy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minTradeSize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinTradeSize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVolumeThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateStakingTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateUserVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'users', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'volumeThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistUser', data: BytesLike): Result;
  }

  
    export namespace EligibilityUpdatedEvent {
      export type InputTuple = [user: AddressLike, volume: BigNumberish, trades: BigNumberish];
      export type OutputTuple = [user: string, volume: bigint, trades: bigint];
      export interface OutputObject {user: string, volume: bigint, trades: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserBlacklistedEvent {
      export type InputTuple = [user: AddressLike];
      export type OutputTuple = [user: string];
      export interface OutputObject {user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserWhitelistedEvent {
      export type InputTuple = [user: AddressLike];
      export type OutputTuple = [user: string];
      export interface OutputObject {user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EligibilityOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): EligibilityOracle;
    waitForDeployment(): Promise<this>;

    interface: EligibilityOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    GOVERNANCE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    KEEPER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    blacklistUser: TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSubsidyPercentage: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isEligibleForSubsidy: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    minTradeSize: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMinTradeSize: TypedContractMethod<
      [_minTradeSize: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setVolumeThreshold: TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateStakingTier: TypedContractMethod<
      [user: AddressLike, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateUserVolume: TypedContractMethod<
      [user: AddressLike, volumeAdd: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    users: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, boolean] & {totalVolume: bigint, tradeCount: bigint, firstTradeTime: bigint, stakingTier: bigint, isWhitelisted: boolean }],
      'view'
    >
    

    
    volumeThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    whitelistUser: TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'GOVERNANCE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'KEEPER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'blacklistUser'): TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSubsidyPercentage'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isEligibleForSubsidy'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'minTradeSize'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinTradeSize'): TypedContractMethod<
      [_minTradeSize: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVolumeThreshold'): TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateStakingTier'): TypedContractMethod<
      [user: AddressLike, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateUserVolume'): TypedContractMethod<
      [user: AddressLike, volumeAdd: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'users'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, boolean] & {totalVolume: bigint, tradeCount: bigint, firstTradeTime: bigint, stakingTier: bigint, isWhitelisted: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'volumeThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'whitelistUser'): TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EligibilityUpdated'): TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'UserBlacklisted'): TypedContractEvent<UserBlacklistedEvent.InputTuple, UserBlacklistedEvent.OutputTuple, UserBlacklistedEvent.OutputObject>;
getEvent(key: 'UserWhitelisted'): TypedContractEvent<UserWhitelistedEvent.InputTuple, UserWhitelistedEvent.OutputTuple, UserWhitelistedEvent.OutputObject>;

    filters: {
      
      'EligibilityUpdated(address,uint256,uint256)': TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
      EligibilityUpdated: TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'UserBlacklisted(address)': TypedContractEvent<UserBlacklistedEvent.InputTuple, UserBlacklistedEvent.OutputTuple, UserBlacklistedEvent.OutputObject>;
      UserBlacklisted: TypedContractEvent<UserBlacklistedEvent.InputTuple, UserBlacklistedEvent.OutputTuple, UserBlacklistedEvent.OutputObject>;
    

      'UserWhitelisted(address)': TypedContractEvent<UserWhitelistedEvent.InputTuple, UserWhitelistedEvent.OutputTuple, UserWhitelistedEvent.OutputObject>;
      UserWhitelisted: TypedContractEvent<UserWhitelistedEvent.InputTuple, UserWhitelistedEvent.OutputTuple, UserWhitelistedEvent.OutputObject>;
    
    };
  }