/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FeeCollectorInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "GOVERNANCE_ROLE" | "POOL_ROLE" | "accumulatedFees" | "addPoolRole" | "distributeFees" | "feeSubsidyPool" | "getAccumulatedFees" | "getRoleAdmin" | "getSplit" | "grantRole" | "hasRole" | "renounceRole" | "revokeRole" | "split" | "stakingRewards" | "supportsInterface" | "totalFeesCollected" | "treasury" | "updateSplit"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeesDistributed" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "RolesUpdated" | "SplitUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GOVERNANCE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'POOL_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addPoolRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'distributeFees', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeSubsidyPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAccumulatedFees', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSplit', values?: undefined): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'split', values?: undefined): string;
encodeFunctionData(functionFragment: 'stakingRewards', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalFeesCollected', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateSplit', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GOVERNANCE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'POOL_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addPoolRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeSubsidyPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSplit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'split', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalFeesCollected', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSplit', data: BytesLike): Result;
  }

  
    export namespace FeesDistributedEvent {
      export type InputTuple = [pool: AddressLike, token: AddressLike, total: BigNumberish, lpAmount: BigNumberish, treasuryAmount: BigNumberish, stakerAmount: BigNumberish, fspAmount: BigNumberish];
      export type OutputTuple = [pool: string, token: string, total: bigint, lpAmount: bigint, treasuryAmount: bigint, stakerAmount: bigint, fspAmount: bigint];
      export interface OutputObject {pool: string, token: string, total: bigint, lpAmount: bigint, treasuryAmount: bigint, stakerAmount: bigint, fspAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RolesUpdatedEvent {
      export type InputTuple = [account: AddressLike, role: BytesLike, granted: boolean];
      export type OutputTuple = [account: string, role: string, granted: boolean];
      export interface OutputObject {account: string, role: string, granted: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SplitUpdatedEvent {
      export type InputTuple = [lp: BigNumberish, treasury: BigNumberish, stakers: BigNumberish, fsp: BigNumberish];
      export type OutputTuple = [lp: bigint, treasury: bigint, stakers: bigint, fsp: bigint];
      export interface OutputObject {lp: bigint, treasury: bigint, stakers: bigint, fsp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FeeCollector extends BaseContract {
    
    connect(runner?: ContractRunner | null): FeeCollector;
    waitForDeployment(): Promise<this>;

    interface: FeeCollectorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    GOVERNANCE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    POOL_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    addPoolRole: TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    distributeFees: TypedContractMethod<
      [pool: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeSubsidyPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAccumulatedFees: TypedContractMethod<
      [pool: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSplit: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint]],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    split: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {lp: bigint, treasury: bigint, stakers: bigint, fsp: bigint }],
      'view'
    >
    

    
    stakingRewards: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalFeesCollected: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updateSplit: TypedContractMethod<
      [_lp: BigNumberish, _treasury: BigNumberish, _stakers: BigNumberish, _fsp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'GOVERNANCE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'POOL_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addPoolRole'): TypedContractMethod<
      [pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeFees'): TypedContractMethod<
      [pool: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeSubsidyPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAccumulatedFees'): TypedContractMethod<
      [pool: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSplit'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'split'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {lp: bigint, treasury: bigint, stakers: bigint, fsp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'stakingRewards'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalFeesCollected'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateSplit'): TypedContractMethod<
      [_lp: BigNumberish, _treasury: BigNumberish, _stakers: BigNumberish, _fsp: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FeesDistributed'): TypedContractEvent<FeesDistributedEvent.InputTuple, FeesDistributedEvent.OutputTuple, FeesDistributedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'RolesUpdated'): TypedContractEvent<RolesUpdatedEvent.InputTuple, RolesUpdatedEvent.OutputTuple, RolesUpdatedEvent.OutputObject>;
getEvent(key: 'SplitUpdated'): TypedContractEvent<SplitUpdatedEvent.InputTuple, SplitUpdatedEvent.OutputTuple, SplitUpdatedEvent.OutputObject>;

    filters: {
      
      'FeesDistributed(address,address,uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<FeesDistributedEvent.InputTuple, FeesDistributedEvent.OutputTuple, FeesDistributedEvent.OutputObject>;
      FeesDistributed: TypedContractEvent<FeesDistributedEvent.InputTuple, FeesDistributedEvent.OutputTuple, FeesDistributedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'RolesUpdated(address,bytes32,bool)': TypedContractEvent<RolesUpdatedEvent.InputTuple, RolesUpdatedEvent.OutputTuple, RolesUpdatedEvent.OutputObject>;
      RolesUpdated: TypedContractEvent<RolesUpdatedEvent.InputTuple, RolesUpdatedEvent.OutputTuple, RolesUpdatedEvent.OutputObject>;
    

      'SplitUpdated(uint16,uint16,uint16,uint16)': TypedContractEvent<SplitUpdatedEvent.InputTuple, SplitUpdatedEvent.OutputTuple, SplitUpdatedEvent.OutputObject>;
      SplitUpdated: TypedContractEvent<SplitUpdatedEvent.InputTuple, SplitUpdatedEvent.OutputTuple, SplitUpdatedEvent.OutputObject>;
    
    };
  }