/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'EligibilityOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EligibilityOracle__factory>
getContractFactory(name: 'FeeCollector', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FeeCollector__factory>
getContractFactory(name: 'FeeSubsidyPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FeeSubsidyPool__factory>
getContractFactory(name: 'IEligibilityOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEligibilityOracle__factory>
getContractFactory(name: 'IRelayerRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRelayerRegistry__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'IFeeCollector', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFeeCollector__factory>
getContractFactory(name: 'Pool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Pool__factory>
getContractFactory(name: 'RelayerRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RelayerRegistry__factory>
getContractFactory(name: 'Router', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Router__factory>
getContractFactory(name: 'SenderTester', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SenderTester__factory>
getContractFactory(name: 'SimplePool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimplePool__factory>
getContractFactory(name: 'SimpleRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleRouter__factory>
getContractFactory(name: 'TestReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TestReceiver__factory>
getContractFactory(name: 'Treasury', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Treasury__factory>
getContractFactory(name: 'TrustedForwarder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TrustedForwarder__factory>

  getContractAt(name: 'EligibilityOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EligibilityOracle>
getContractAt(name: 'FeeCollector', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FeeCollector>
getContractAt(name: 'FeeSubsidyPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FeeSubsidyPool>
getContractAt(name: 'IEligibilityOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEligibilityOracle>
getContractAt(name: 'IRelayerRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRelayerRegistry>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'IFeeCollector', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFeeCollector>
getContractAt(name: 'Pool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Pool>
getContractAt(name: 'RelayerRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RelayerRegistry>
getContractAt(name: 'Router', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Router>
getContractAt(name: 'SenderTester', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SenderTester>
getContractAt(name: 'SimplePool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimplePool>
getContractAt(name: 'SimpleRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleRouter>
getContractAt(name: 'TestReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TestReceiver>
getContractAt(name: 'Treasury', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Treasury>
getContractAt(name: 'TrustedForwarder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TrustedForwarder>

  deployContract(name: 'EligibilityOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EligibilityOracle>
deployContract(name: 'FeeCollector', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeCollector>
deployContract(name: 'FeeSubsidyPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeSubsidyPool>
deployContract(name: 'IEligibilityOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEligibilityOracle>
deployContract(name: 'IRelayerRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRelayerRegistry>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IFeeCollector', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeCollector>
deployContract(name: 'Pool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pool>
deployContract(name: 'RelayerRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RelayerRegistry>
deployContract(name: 'Router', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Router>
deployContract(name: 'SenderTester', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SenderTester>
deployContract(name: 'SimplePool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimplePool>
deployContract(name: 'SimpleRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleRouter>
deployContract(name: 'TestReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestReceiver>
deployContract(name: 'Treasury', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Treasury>
deployContract(name: 'TrustedForwarder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TrustedForwarder>

  deployContract(name: 'EligibilityOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EligibilityOracle>
deployContract(name: 'FeeCollector', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeCollector>
deployContract(name: 'FeeSubsidyPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeSubsidyPool>
deployContract(name: 'IEligibilityOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEligibilityOracle>
deployContract(name: 'IRelayerRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRelayerRegistry>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IFeeCollector', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeCollector>
deployContract(name: 'Pool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pool>
deployContract(name: 'RelayerRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RelayerRegistry>
deployContract(name: 'Router', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Router>
deployContract(name: 'SenderTester', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SenderTester>
deployContract(name: 'SimplePool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimplePool>
deployContract(name: 'SimpleRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleRouter>
deployContract(name: 'TestReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestReceiver>
deployContract(name: 'Treasury', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Treasury>
deployContract(name: 'TrustedForwarder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TrustedForwarder>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  