/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PoolInterface extends Interface {
    getFunction(nameOrSignature: "FEE" | "addLiquidityFor" | "getAmountOut" | "getLpInfo" | "getReserves" | "lpShares" | "removeLiquidityFor" | "reserve0" | "reserve1" | "router" | "swap" | "token0" | "token1" | "totalLpShares"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddLiquidity" | "RemoveLiquidity" | "Swap"): EventFragment;

    encodeFunctionData(functionFragment: 'FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addLiquidityFor', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getAmountOut', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLpInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'lpShares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeLiquidityFor', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'reserve0', values?: undefined): string;
encodeFunctionData(functionFragment: 'reserve1', values?: undefined): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;
encodeFunctionData(functionFragment: 'swap', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'token0', values?: undefined): string;
encodeFunctionData(functionFragment: 'token1', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalLpShares', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addLiquidityFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLpInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lpShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidityFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserve0', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserve1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token0', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLpShares', data: BytesLike): Result;
  }

  
    export namespace AddLiquidityEvent {
      export type InputTuple = [user: AddressLike, amount0: BigNumberish, amount1: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [user: string, amount0: bigint, amount1: bigint, shares: bigint];
      export interface OutputObject {user: string, amount0: bigint, amount1: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveLiquidityEvent {
      export type InputTuple = [user: AddressLike, shares: BigNumberish, amount0: BigNumberish, amount1: BigNumberish];
      export type OutputTuple = [user: string, shares: bigint, amount0: bigint, amount1: bigint];
      export interface OutputObject {user: string, shares: bigint, amount0: bigint, amount1: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapEvent {
      export type InputTuple = [user: AddressLike, tokenIn: AddressLike, amountIn: BigNumberish, amountOut: BigNumberish];
      export type OutputTuple = [user: string, tokenIn: string, amountIn: bigint, amountOut: bigint];
      export interface OutputObject {user: string, tokenIn: string, amountIn: bigint, amountOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Pool extends BaseContract {
    
    connect(runner?: ContractRunner | null): Pool;
    waitForDeployment(): Promise<this>;

    interface: PoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addLiquidityFor: TypedContractMethod<
      [amount0: BigNumberish, amount1: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getAmountOut: TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getLpInfo: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint] & {shares: bigint, total: bigint, sharePercent: bigint }],
      'view'
    >
    

    
    getReserves: TypedContractMethod<
      [],
      [[bigint, bigint]],
      'view'
    >
    

    
    lpShares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    removeLiquidityFor: TypedContractMethod<
      [shares: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    reserve0: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reserve1: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    swap: TypedContractMethod<
      [tokenIn: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    token0: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token1: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalLpShares: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addLiquidityFor'): TypedContractMethod<
      [amount0: BigNumberish, amount1: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAmountOut'): TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLpInfo'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint] & {shares: bigint, total: bigint, sharePercent: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getReserves'): TypedContractMethod<
      [],
      [[bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'lpShares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'removeLiquidityFor'): TypedContractMethod<
      [shares: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reserve0'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reserve1'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [tokenIn: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token0'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token1'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalLpShares'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'AddLiquidity'): TypedContractEvent<AddLiquidityEvent.InputTuple, AddLiquidityEvent.OutputTuple, AddLiquidityEvent.OutputObject>;
getEvent(key: 'RemoveLiquidity'): TypedContractEvent<RemoveLiquidityEvent.InputTuple, RemoveLiquidityEvent.OutputTuple, RemoveLiquidityEvent.OutputObject>;
getEvent(key: 'Swap'): TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;

    filters: {
      
      'AddLiquidity(address,uint256,uint256,uint256)': TypedContractEvent<AddLiquidityEvent.InputTuple, AddLiquidityEvent.OutputTuple, AddLiquidityEvent.OutputObject>;
      AddLiquidity: TypedContractEvent<AddLiquidityEvent.InputTuple, AddLiquidityEvent.OutputTuple, AddLiquidityEvent.OutputObject>;
    

      'RemoveLiquidity(address,uint256,uint256,uint256)': TypedContractEvent<RemoveLiquidityEvent.InputTuple, RemoveLiquidityEvent.OutputTuple, RemoveLiquidityEvent.OutputObject>;
      RemoveLiquidity: TypedContractEvent<RemoveLiquidityEvent.InputTuple, RemoveLiquidityEvent.OutputTuple, RemoveLiquidityEvent.OutputObject>;
    

      'Swap(address,address,uint256,uint256)': TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
      Swap: TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
    
    };
  }