/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RouterInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidity" | "createPool" | "getPool" | "isTrustedForwarder" | "registerPool" | "swap"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PoolCreated" | "PoolRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'addLiquidity', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPool', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getPool', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isTrustedForwarder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerPool', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'swap', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTrustedForwarder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
  }

  
    export namespace PoolCreatedEvent {
      export type InputTuple = [tokenA: AddressLike, tokenB: AddressLike, pool: AddressLike];
      export type OutputTuple = [tokenA: string, tokenB: string, pool: string];
      export interface OutputObject {tokenA: string, tokenB: string, pool: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PoolRegisteredEvent {
      export type InputTuple = [tokenA: AddressLike, tokenB: AddressLike, pool: AddressLike];
      export type OutputTuple = [tokenA: string, tokenB: string, pool: string];
      export interface OutputObject {tokenA: string, tokenB: string, pool: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Router extends BaseContract {
    
    connect(runner?: ContractRunner | null): Router;
    waitForDeployment(): Promise<this>;

    interface: RouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountA: BigNumberish, amountB: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createPool: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    getPool: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [string],
      'view'
    >
    

    
    isTrustedForwarder: TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerPool: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    swap: TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountA: BigNumberish, amountB: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPool'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPool'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isTrustedForwarder'): TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerPool'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'PoolCreated'): TypedContractEvent<PoolCreatedEvent.InputTuple, PoolCreatedEvent.OutputTuple, PoolCreatedEvent.OutputObject>;
getEvent(key: 'PoolRegistered'): TypedContractEvent<PoolRegisteredEvent.InputTuple, PoolRegisteredEvent.OutputTuple, PoolRegisteredEvent.OutputObject>;

    filters: {
      
      'PoolCreated(address,address,address)': TypedContractEvent<PoolCreatedEvent.InputTuple, PoolCreatedEvent.OutputTuple, PoolCreatedEvent.OutputObject>;
      PoolCreated: TypedContractEvent<PoolCreatedEvent.InputTuple, PoolCreatedEvent.OutputTuple, PoolCreatedEvent.OutputObject>;
    

      'PoolRegistered(address,address,address)': TypedContractEvent<PoolRegisteredEvent.InputTuple, PoolRegisteredEvent.OutputTuple, PoolRegisteredEvent.OutputObject>;
      PoolRegistered: TypedContractEvent<PoolRegisteredEvent.InputTuple, PoolRegisteredEvent.OutputTuple, PoolRegisteredEvent.OutputObject>;
    
    };
  }