/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SenderTesterInterface extends Interface {
    getFunction(nameOrSignature: "getLastSender" | "isTrustedForwarder" | "lastSender" | "test"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getLastSender', values?: undefined): string;
encodeFunctionData(functionFragment: 'isTrustedForwarder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastSender', values?: undefined): string;
encodeFunctionData(functionFragment: 'test', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getLastSender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTrustedForwarder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastSender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'test', data: BytesLike): Result;
  }

  

  export interface SenderTester extends BaseContract {
    
    connect(runner?: ContractRunner | null): SenderTester;
    waitForDeployment(): Promise<this>;

    interface: SenderTesterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getLastSender: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isTrustedForwarder: TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lastSender: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    test: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getLastSender'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isTrustedForwarder'): TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastSender'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'test'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }