/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SimpleRouterInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidity" | "createPool" | "getPool" | "swap"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addLiquidity', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPool', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getPool', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'swap', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
  }

  

  export interface SimpleRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleRouter;
    waitForDeployment(): Promise<this>;

    interface: SimpleRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountA: BigNumberish, amountB: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createPool: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    getPool: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [string],
      'view'
    >
    

    
    swap: TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, amountA: BigNumberish, amountB: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPool'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPool'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }