/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { SenderTester, SenderTesterInterface } from "../SenderTester.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "trustedForwarder",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "getLastSender",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "forwarder",
        "type": "address"
      }
    ],
    "name": "isTrustedForwarder",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lastSender",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "test",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a060405234801561000f575f80fd5b506040516102ed3803806102ed83398101604081905261002e9161003f565b6001600160a01b031660805261006c565b5f6020828403121561004f575f80fd5b81516001600160a01b0381168114610065575f80fd5b9392505050565b60805161026361008a5f395f81816099015261011b01526102635ff3fe608060405234801561000f575f80fd5b506004361061004a575f3560e01c806314ca3c7c1461004e578063256fec8814610077578063572b6c0514610089578063f8a8fd6d146100d9575b5f80fd5b5f546001600160a01b03165b6040516001600160a01b0390911681526020015b60405180910390f35b5f5461005a906001600160a01b031681565b6100c961009736600461017f565b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0390811691161490565b604051901515815260200161006e565b6100e16100e3565b005b6100eb61010c565b5f80546001600160a01b0319166001600160a01b0392909216919091179055565b5f366014336001600160a01b037f0000000000000000000000000000000000000000000000000000000000000000161480156101485750808210155b15610177575f3661015983856101ac565b6101649282906101d1565b61016d916101f8565b60601c9250505090565b339250505090565b5f6020828403121561018f575f80fd5b81356001600160a01b03811681146101a5575f80fd5b9392505050565b818103818111156101cb57634e487b7160e01b5f52601160045260245ffd5b92915050565b5f80858511156101df575f80fd5b838611156101eb575f80fd5b5050820193919092039150565b6bffffffffffffffffffffffff1981358181169160148510156102255780818660140360031b1b83161692505b50509291505056fea2646970667358221220f6d1ec5c4b0b33e89c5cacd38c9992ff1534144d549f34310f94b056876ac57964736f6c63430008180033";

  
      type SenderTesterConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SenderTesterConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SenderTester__factory extends ContractFactory {
    
      constructor(...args: SenderTesterConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(trustedForwarder: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(trustedForwarder, overrides || {});
    };
    override deploy(trustedForwarder: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(trustedForwarder, overrides || {}) as Promise<SenderTester & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SenderTester__factory {
      return super.connect(runner) as SenderTester__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SenderTesterInterface {
      return new Interface(_abi) as SenderTesterInterface;
    }
    
    override attach(address: string | Addressable): SenderTester {
      return super.attach(address) as SenderTester;
    }
  static connect(address: string, runner?: ContractRunner | null): SenderTester {
      return new Contract(address, _abi, runner) as unknown as SenderTester;
    }
  }

  
  