/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { TestReceiver, TestReceiverInterface } from "../TestReceiver.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getValue",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "newValue",
        "type": "uint256"
      }
    ],
    "name": "setValue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "value",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060b78061001c5f395ff3fe6080604052348015600e575f80fd5b5060043610603a575f3560e01c80632096525514603e5780633fa4f2451460535780635524107714605a575b5f80fd5b5f545b60405190815260200160405180910390f35b60415f5481565b60696065366004606b565b5f55565b005b5f60208284031215607a575f80fd5b503591905056fea2646970667358221220c4ddc718e4f3c0c29139de812e9010f0f743adb98806b0e6d5f9cf38065c393b64736f6c63430008180033";

  
      type TestReceiverConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: TestReceiverConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class TestReceiver__factory extends ContractFactory {
    
      constructor(...args: TestReceiverConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<TestReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): TestReceiver__factory {
      return super.connect(runner) as TestReceiver__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): TestReceiverInterface {
      return new Interface(_abi) as TestReceiverInterface;
    }
    
    override attach(address: string | Addressable): TestReceiver {
      return super.attach(address) as TestReceiver;
    }
  static connect(address: string, runner?: ContractRunner | null): TestReceiver {
      return new Contract(address, _abi, runner) as unknown as TestReceiver;
    }
  }

  
  