/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { TrustedForwarder, TrustedForwarderInterface } from "../TrustedForwarder.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "signature",
        "type": "bytes"
      }
    ],
    "name": "execute",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "isTrustedForwarder",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "forwarder",
        "type": "address"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b50335f908152602081905260409020805460ff19166001179055610319806100365f395ff3fe608060405234801561000f575f80fd5b506004361061003f575f3560e01c8063572b6c051461004357806363a9c3d714610079578063d4fa4534146100a4575b5f80fd5b61006561005136600461018b565b5f6020819052908152604090205460ff1681565b604051901515815260200160405180910390f35b61006561008736600461018b565b6001600160a01b03165f9081526020819052604090205460ff1690565b6100656100b2366004610248565b335f9081526020819052604081205460ff1661010d5760405162461bcd60e51b815260206004820152601660248201527527b7363c903a393ab9ba32b2103337b93bb0b93232b960511b604482015260640160405180910390fd5b5f846001600160a01b03168460405161012691906102b7565b5f604051808303815f865af19150503d805f811461015f576040519150601f19603f3d011682016040523d82523d5f602084013e610164565b606091505b50909695505050505050565b80356001600160a01b0381168114610186575f80fd5b919050565b5f6020828403121561019b575f80fd5b6101a482610170565b9392505050565b634e487b7160e01b5f52604160045260245ffd5b5f82601f8301126101ce575f80fd5b813567ffffffffffffffff808211156101e9576101e96101ab565b604051601f8301601f19908116603f01168101908282118183101715610211576102116101ab565b81604052838152866020858801011115610229575f80fd5b836020870160208301375f602085830101528094505050505092915050565b5f805f6060848603121561025a575f80fd5b61026384610170565b9250602084013567ffffffffffffffff8082111561027f575f80fd5b61028b878388016101bf565b935060408601359150808211156102a0575f80fd5b506102ad868287016101bf565b9150509250925092565b5f82515f5b818110156102d657602081860181015185830152016102bc565b505f92019182525091905056fea264697066735822122081c03e9330e73e9641c842afae232968329b1a15ca6f3fc44c86709a1bd603ec64736f6c63430008180033";

  
      type TrustedForwarderConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: TrustedForwarderConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class TrustedForwarder__factory extends ContractFactory {
    
      constructor(...args: TrustedForwarderConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<TrustedForwarder & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): TrustedForwarder__factory {
      return super.connect(runner) as TrustedForwarder__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): TrustedForwarderInterface {
      return new Interface(_abi) as TrustedForwarderInterface;
    }
    
    override attach(address: string | Addressable): TrustedForwarder {
      return super.attach(address) as TrustedForwarder;
    }
  static connect(address: string, runner?: ContractRunner | null): TrustedForwarder {
      return new Contract(address, _abi, runner) as unknown as TrustedForwarder;
    }
  }

  
  