/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEligibilityOracle, IEligibilityOracleInterface } from "../../FeeSubsidyPool.sol/IEligibilityOracle.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "isEligibleForSubsidy",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IEligibilityOracle__factory {
    static readonly abi = _abi;
    static createInterface(): IEligibilityOracleInterface {
      return new Interface(_abi) as IEligibilityOracleInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEligibilityOracle {
      return new Contract(address, _abi, runner) as unknown as IEligibilityOracle;
    }
  }
  