/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRelayerRegistry, IRelayerRegistryInterface } from "../../FeeSubsidyPool.sol/IRelayerRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "isRelayer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IRelayerRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IRelayerRegistryInterface {
      return new Interface(_abi) as IRelayerRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRelayerRegistry {
      return new Contract(address, _abi, runner) as unknown as IRelayerRegistry;
    }
  }
  