/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFeeSubsidyPool, IFeeSubsidyPoolInterface } from "../../Treasury.sol/IFeeSubsidyPool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "fundPool",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IFeeSubsidyPool__factory {
    static readonly abi = _abi;
    static createInterface(): IFeeSubsidyPoolInterface {
      return new Interface(_abi) as IFeeSubsidyPoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFeeSubsidyPool {
      return new Contract(address, _abi, runner) as unknown as IFeeSubsidyPool;
    }
  }
  