/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFeeCollector, IFeeCollectorInterface } from "../../Pool.sol/IFeeCollector.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "pool",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "distributeFees",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IFeeCollector__factory {
    static readonly abi = _abi;
    static createInterface(): IFeeCollectorInterface {
      return new Interface(_abi) as IFeeCollectorInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFeeCollector {
      return new Contract(address, _abi, runner) as unknown as IFeeCollector;
    }
  }
  