/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PoolInterface extends Interface {
    getFunction(nameOrSignature: "FEE" | "PRECISION" | "addLiquidity" | "feeCollector" | "getAmountOut" | "getLpInfo" | "getReserves" | "lpShares" | "removeLiquidity" | "reserve0" | "reserve1" | "setFeeCollector" | "swap" | "token0" | "token1" | "totalLpShares"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeeCollectorUpdated" | "LiquidityAdded" | "LiquidityRemoved" | "Swap"): EventFragment;

    encodeFunctionData(functionFragment: 'FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PRECISION', values?: undefined): string;
encodeFunctionData(functionFragment: 'addLiquidity', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeCollector', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAmountOut', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLpInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'lpShares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeLiquidity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reserve0', values?: undefined): string;
encodeFunctionData(functionFragment: 'reserve1', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFeeCollector', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'swap', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'token0', values?: undefined): string;
encodeFunctionData(functionFragment: 'token1', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalLpShares', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PRECISION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLpInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lpShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserve0', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserve1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token0', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLpShares', data: BytesLike): Result;
  }

  
    export namespace FeeCollectorUpdatedEvent {
      export type InputTuple = [oldCollector: AddressLike, newCollector: AddressLike];
      export type OutputTuple = [oldCollector: string, newCollector: string];
      export interface OutputObject {oldCollector: string, newCollector: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityAddedEvent {
      export type InputTuple = [provider: AddressLike, amount0: BigNumberish, amount1: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [provider: string, amount0: bigint, amount1: bigint, shares: bigint];
      export interface OutputObject {provider: string, amount0: bigint, amount1: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityRemovedEvent {
      export type InputTuple = [provider: AddressLike, amount0: BigNumberish, amount1: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [provider: string, amount0: bigint, amount1: bigint, shares: bigint];
      export interface OutputObject {provider: string, amount0: bigint, amount1: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapEvent {
      export type InputTuple = [sender: AddressLike, tokenIn: AddressLike, amountIn: BigNumberish, amountOut: BigNumberish];
      export type OutputTuple = [sender: string, tokenIn: string, amountIn: bigint, amountOut: bigint];
      export interface OutputObject {sender: string, tokenIn: string, amountIn: bigint, amountOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Pool extends BaseContract {
    
    connect(runner?: ContractRunner | null): Pool;
    waitForDeployment(): Promise<this>;

    interface: PoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PRECISION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addLiquidity: TypedContractMethod<
      [amount0: BigNumberish, amount1: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeCollector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAmountOut: TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getLpInfo: TypedContractMethod<
      [provider: AddressLike, ],
      [[bigint, bigint, bigint] & {shares: bigint, amount0: bigint, amount1: bigint }],
      'view'
    >
    

    
    getReserves: TypedContractMethod<
      [],
      [[bigint, bigint]],
      'view'
    >
    

    
    lpShares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    removeLiquidity: TypedContractMethod<
      [shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reserve0: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reserve1: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setFeeCollector: TypedContractMethod<
      [_feeCollector: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    swap: TypedContractMethod<
      [tokenIn: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    token0: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token1: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalLpShares: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PRECISION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [amount0: BigNumberish, amount1: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeCollector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAmountOut'): TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLpInfo'): TypedContractMethod<
      [provider: AddressLike, ],
      [[bigint, bigint, bigint] & {shares: bigint, amount0: bigint, amount1: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getReserves'): TypedContractMethod<
      [],
      [[bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'lpShares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'removeLiquidity'): TypedContractMethod<
      [shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reserve0'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reserve1'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setFeeCollector'): TypedContractMethod<
      [_feeCollector: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [tokenIn: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token0'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token1'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalLpShares'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'FeeCollectorUpdated'): TypedContractEvent<FeeCollectorUpdatedEvent.InputTuple, FeeCollectorUpdatedEvent.OutputTuple, FeeCollectorUpdatedEvent.OutputObject>;
getEvent(key: 'LiquidityAdded'): TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
getEvent(key: 'LiquidityRemoved'): TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
getEvent(key: 'Swap'): TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;

    filters: {
      
      'FeeCollectorUpdated(address,address)': TypedContractEvent<FeeCollectorUpdatedEvent.InputTuple, FeeCollectorUpdatedEvent.OutputTuple, FeeCollectorUpdatedEvent.OutputObject>;
      FeeCollectorUpdated: TypedContractEvent<FeeCollectorUpdatedEvent.InputTuple, FeeCollectorUpdatedEvent.OutputTuple, FeeCollectorUpdatedEvent.OutputObject>;
    

      'LiquidityAdded(address,uint256,uint256,uint256)': TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
      LiquidityAdded: TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
    

      'LiquidityRemoved(address,uint256,uint256,uint256)': TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
      LiquidityRemoved: TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
    

      'Swap(address,address,uint256,uint256)': TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
      Swap: TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
    
    };
  }